### ISSUE TITLE
Missing man page

### ISSUE THREAD

**Issue by Morganamilo** [dylanaraps/saur#6]
I see there is a man page in this repo although it is not included in your PKGBUILD. So when installing through the AUR the manpage is never installed.

On a similar note most other helpers tend to have their man pages in section 8 as they require root to work. aurutils is an exception to this as it does it's things in a local repo. You might want to consider changing the section.

**Comment by dylanaraps** [comment]
Fixed.

`cower` also puts it's man page in section 1 so I don't think it's an issue.
